spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: SUchunyang0511
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 192.168.1.4
    port: 5672
    userName: guest
    password: guest
mybatis:
#  驼峰命名的配置
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  mybatis的xml文件位置
  mapper-locations: classpath:mappers/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 120